//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchadModels.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class InvoiceDetail
    {
        public int Id { get; set; }
        [Display(Name = "Id de factura")]
        public int InvoiceId { get; set; }
        [Display(Name = "Cantidad")]
        public int Qty { get; set; }
        [Display(Name = "Precio Unitario")]
        public decimal Price { get; set; }
        [Display(Name = "Total Itbis")]
        public decimal TotalItbis { get; set; }
        public decimal SubTotal { get; set; }
        public decimal Total { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
